### ISSUE TITLE
Користи decimal а не float

### ISSUE THREAD

**Issue by gdamjan** [skopjehacklab/kalkulator.ot.mk#1]
Финансиски пресметки треба да се прават со „Decimal“ броеви, а не со „Float“.

во float 0.1 + 0.2 не е баш еднакво на 0.3

Decimal типот на бројки складира точно онолку децимали колку се потребни во пресметките во финансискиот систем и заокружувањето се прави при секоја пресметка според тие стандарди. Кај нас се тоа веројатно 2 децимали.

**Comment by vladan** [comment]
Се препиша во elm.

**Comment by gdamjan** [comment]
тоа не го рашава проблемот, пошто elm ги користи истите броеви како и javascript кои се 56bit floats (т.е прилично лоши)

треба да се види еден од овие пакети:
https://package.elm-lang.org/packages/prikhi/decimal/latest/
https://package.elm-lang.org/packages/torreyatcitty/the-best-decimal/latest/

**Comment by vladan** [comment]
Немогуче е да се додадат "Decimal" броеви пошто Elm sucks и треба цел кодбејс да се смени, ќе изгледа многу за никаде, има нови пресметки и нов начин на пресметување од нето во бруто, така да не верувам дека ќе треба ова воопшто.

**Comment by dimitrovskif** [comment]
Секое множење на цел број со 2 цифрен процент ќе даде број со максимум два децимали. Ако заокружувањето се прави при секоја стапка, резултатот ќе биде потполно точен.

* платата е 5-9 цифри
* процентите се макс 4 децимали
* прецизноста на Float e 15-17 цифри

Важно е само заокружувањето да е точно.
