### ISSUE TITLE
Проверка дали пресметките се точни за 2015.

### ISSUE THREAD

**Issue by glisha** [skopjehacklab/kalkulator.ot.mk#12]
Ваљда треба да се направи проверка дали пресметките се точни. Во смисла некои коефициенти да не се сменети?

Или да се посочат ажурни документи:
http://dl.dropbox.com/u/13597364/upatstvo_bruto_plata.pdf
http://www.ujp.gov.mk/mk/javnost/soopstenija/pogledni/356

**Comment by novica** [comment]
нели апликацијава секако не работеше? без разлика на тоа какви коефиценти има?

**Comment by gdamjan** [comment]
@novica  Нема таков bug дека „апликацијата не работи“

**Comment by novica** [comment]
Еве ги официјалните податоци за 2015

1. Prose~na isplatena bruto plata za 2015            31.644,00
2. Najniska osnovica za danoci i
    pridonesi za 2015 (31.644,00 h 50%)                   15.822,00
3. Najvisoka osnovica za pridonesi
    za 2015 (6 h 31.644,00)                                          189.864,00
4. Minimalna plata vo RM za 2015 godina
    (vo neto iznos)                                                        9.590,00
5. Li~no osloboduvawe za 2015 godina                     7.320,00

**Comment by novica** [comment]
а со овој Bug до каде е? 
https://github.com/skopjehacklab/kalkulator.ot.mk/issues/8
