### ISSUE TITLE
Минат труд

### ISSUE THREAD

**Issue by ptofevski** [skopjehacklab/kalkulator.ot.mk#14]
Фали минатиот труд од 0.5 по година стаж, треба едно поле со број на години и да се пресмета зголемување на нетото.

**Comment by vladan** [comment]
@ptofevski фала! Имаш некој официјален линк/документ за ова?

**Comment by ptofevski** [comment]
Член 18 од Општиот колективен договор.
Основната плата на работникот се зголемува за 0.5% за секоја навршена година работен стаж, а најмногу до 20%

http://www.pravdiko.mk/wp-content/uploads/2013/11/Opsht-kolektiven-dogovor-za-javniot-sektor.pdf

**Comment by vladan** [comment]
@ptofevski Извини најнапред за големово каснење. Ако разбрав добро, основната плата треба да се зголемува за 0.5% годишно, ама со тоа се зголемува и бруто платата и даноците/продонесите соодветно. Ако ти ја внесеш сегашната плата, после 10 години работно искуство, значи треба да ти е 5% покачена од иницијалната (од пред 10 години) и ќе ти ги пресмета сите даноци/придонеси и бруто за оваа година, што не менува ништо на база на работно искуство.

Не знам дали сум сфатил добро или не, ако не те молам за пошироко објаснување.

**Comment by novica** [comment]
Мислам дека за потребите на функционирање на оваа апликација минат труд не игра улога. Вредноста на минат труд секако влегува во бруто платата (како што влегуваат прекувремените часови и други активности) и од брутото се пресметува нетото.

**Comment by ptofevski** [comment]
@novica @vladan Еве пример јас имам нето плата и не знам колку ми е брутото, сакам да си пресметам колку треба да ми биде платата со минатиот труд. И да @vladan точно така : основната плата треба да се зголемува за 0.5% годишно, ама со тоа се зголемува и бруто платата и даноците/продонесите соодветно. Ако ти ја внесеш сегашната плата, после 10 години работно искуство, значи треба да ти е 5% покачена од иницијалната (од пред 10 години) апликацијава ќе ти ги пресмета сите даноци/придонеси и бруто за оваа година, што не менува ништо на база на работно искуство.

**Comment by vladan** [comment]
Ова ми има смисла само ако сакаш да си ја пресметаш нето/бруто платата за некоја мината година. Ако ја внесеш нето платата за тековнава година, што би смениле годините на работно искуство?

**Comment by ptofevski** [comment]
Еве пример во 2017та имав 11 години и 6 месеци стаж, сега во 2018та имам 12 години и 6 месеци стаж, што значи фирмата треба да ми ја зголеми платата за 0.5% и сакам да пресметам колку ќе ми биде новата плата.

**Comment by gdamjan** [comment]
апликацијата моментално нема можност да пресметува нето ←→ бруто за други години освен сегашната, тоа би била дополнителна комплексност за ваква проста апликација.

**Comment by spion** [comment]
може да има као табела / section со само две полиња 

Проектирана минимална покачена плата (1 година подоцна, +0.5%)
* бруто --- value
* нето --- value

**Comment by vladan** [comment]
За пресметување на придонеси и конверзија на нето/бруто за минати години ќе нѝ треба регистар од основиците, личните ослободувања, минимална бруто/нето плата, референтни вредности, и т.н. **за секоја година посебно** ... што е прилично комплексно по мое мислење. Не знам дали вреди и колку ќе им значи на луѓе да можат да гледаат која им била платата и/или која ќе им биде со минимално покачување до година.

За во иднина (проектираната плата 1 година подоцна), ќе мора да има некакви референтни вредности. Значи иднина отпаѓа од игра пошто не можеме да ги знаеме основиците, ослободувањата и т.н.
