### ISSUE TITLE
Проблем со пресметка на персонален данок на високи плати

### ISSUE THREAD

**Issue by veljjanoski** [skopjehacklab/kalkulator.ot.mk#15]
Здраво,

Изгледа дека има проблем со пресметката на НЕТО/БРУТО за високи плати:

Внесувам НЕТО: 1000000 се пресметува БРУТО: 1520924
Внесувам БРУТО: 1520924 се пресметува НЕТО: 1237086 (очекувам да е 1000000 според тоа претходно)
Внесувам НЕТО: 1237086, се пресметува БРУТО: 1881785 ...

Се извинувам ако се работи за погрешно разбирање од моја страна... 

Поздрав

ПС: Со оглед на фактот што во 2016 највисоката нето плата во МК била 225.000 евра не е лошо да се пресмета колку е персоналецот :)

**Comment by veljjanoski** [comment]
Во насловот погоре напишав проблем со персоналниот данок, поради тоа што без никакво ослободување персоналецот (без пензиско, здравствено итн пример за хонорарна работа) е БРУТО - 10% или НЕТО + 11,111%.

Пример ако нето износот е 1,000,000 ден, логично е персоналниот данок да е максимум 111,110 ден, а според калкулаторот излегува повеќе. Може да е помалку ако се земе во предвид личното ослободување но не повеќе... или барем не би требало :)

Фала и поздрав

**Comment by vladan** [comment]
@veljjanoski може да пробаш пак овде http://plata.m.ie.mk/? Изгледа ко да е поправено.

**Comment by veljjanoski** [comment]
Проблемот е поправен и од првиот и од вториот коментар, фала @vladan you rock! :smile:
