### ISSUE TITLE
Даночна основица замрзната на макс 90000

### ISSUE THREAD

**Issue by mironm** [skopjehacklab/kalkulator.ot.mk#26]
Во случаи кога се внесуваат износи на бруто плати од 140000 даночната основица останува замрзната на 90000.

**Comment by gdamjan** [comment]
тоа ако не се лажам е според Член 84 од ЗАКОН ЗА ДАНОКОТ НА ЛИЧЕН ДОХОД 
http://ujp.gov.mk/e/regulativa/opis/337

**Comment by mironm** [comment]
Член 24

(1) Одредбите од членовите од 11, 84 и 87 од овој закон кои се однесуваат на стапките по кои ...... нема да се применуваат од 1 јануари 2020 година до
31 декември 2022 година.

**Comment by gdamjan** [comment]
кул промена :)

**Comment by vladan** [comment]
Треба да е поправено, @mironm ако можеш провери и затвори то issue-во. Фала што го пријави проблемот!

**Comment by mironm** [comment]
Изгледа исправено. Фала на брза реакција
