### ISSUE TITLE
Недостасува title атрибут на бруто/нето полињата како опис за корисниците

### ISSUE THREAD

**Issue by gnud** [skopjehacklab/kalkulator.ot.mk#28]
Ако се стават tooltips (title) атрибути со дефиниција што значи бруто/нето на input полињата би било супер.

Ако некој ја состави дефиницијата ќе напрам PR.

**Comment by igorstama** [comment]
* **Бруто**, износ кој ја вклучува чистата плата што ја добива работникот (нето-плата) заедно со сите јавни давачки (даноци и придонеси), во бруто-платата се вклучени надоместоците кои ги добиваат вработените за храна и за превоз

* **Нето**, чистата плата што ја добива работникот на својата трансакциска сметка

**Comment by gnud** [comment]
Ок, ќе направам сега PR, само да расчепкам како се билда.

**Comment by vladan** [comment]
Не знам ... дали има потреба од објаснување што е бруто, а што нето?
Исто така, калкулаторов не рачуна храна и превоз, освен ако тоа не е даночното ослободување?
Како и да е, сакате да ставиме волку детален опис во лабела на инпут поле?
