### ISSUE TITLE
Нема ограничување за највисока стапка на придонеси

### ISSUE THREAD

**Issue by gspirovski** [skopjehacklab/kalkulator.ot.mk#30]
Нема ограничување за највисоката стапка за придонеси, имено:

http://www.ujp.gov.mk/mk/javnost/soopstenija/pogledni/842

Примерно, за 1.000.000 денари дава 188.000 денари придонеси за ПИО, а треба да дава 123.752 денари.

**Comment by vladan** [comment]
Фала на пријавата @gspirovski, и јас го приметив ова пред некој ден. Ќе гледам викендов да го поправам.
